version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_nutricionista
    restart: always
    environment:
      POSTGRES_USER: nutricionista
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: nutricionista_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
